language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "pypy"
install:
  # For Python 2.6 support
  - "pip install ordereddict --use-mirrors"
  - "pip install coveralls"
script: nosetests
after_success:
  - coveralls